tests/pp/err.cpp:5:2: error: "Failure2"
#error "Failure2"
 ^
1 error generated.
