tests/pp/errspace.cpp:5:5: error: "Failure"
        #  error "Failure"
           ^
1 error generated.
